### ISSUE TITLE
Not blocking notifications when time set to wrap

### ISSUE THREAD

**Issue by Nanorithm** [eclair4151/NotiBlock#1]
Hey first of all thank you so much for this tweak! 

I'm having an issue trying to block notifications from 10PM - 1:30PM the next day. My initial impression is that there's a logic error in processing wrapping times as I'm still getting notifications currently. I have my filter set to always block MS Teams notifications, still show in notification center, start 10PM, end 1:30PM, M-F. I can provide screenshots or anything else that may be needed to help.

Thanks again for this, I've been looking for a tweak like this for months!

**Comment by eclair4151** [comment]
Hey, yea i had another user report that as well. I am looking into it :) hopefully will have a fix later today!

**Comment by eclair4151** [comment]
fixed with 41021e3
