### ISSUE TITLE
can't create new filters

### ISSUE THREAD

**Issue by phutureboy** [eclair4151/NotiBlock#10]
Hi there, first of all congrats for your great tweak which is one of the very few I JB my iphone for.
Now, since I JBd my iOS 14.1 I could fortunately re-install Notiblock but only the old filters I had created under iOS 13 work and I cannot create new filters. I can open the "Notification Filter List" window, I can press the "+" sign and open a "New Notification Filter" window but all fields are dead : I cannot write anything in the "Filter Name" field, cannot select the "Block if" or "Filter Type", etc... Any idea how to "unlock" the feature ?

**Comment by eclair4151** [comment]
This should have been fixed in he most recent update. Refresh your sources and make sure you are installing version 0.0.4

**Comment by phutureboy** [comment]
OK, good news then, yet I refresh my sources every couple of days even a few minutes ago and all I see is 0.0.2

**Comment by eclair4151** [comment]
Ah ok, well I can’t quite help with that. It’s on the big boss repo so I guess make sure you have that one and there aren’t errors while refreshing. If you can’t get it to refresh you can always manually download the deb from the packages folder in this repo and install it with Filza.

**Comment by phutureboy** [comment]
you mean the apt.thebigboss.org/repofiles/cydia/ right ?

**Comment by eclair4151** [comment]
Yup

**Comment by phutureboy** [comment]
ok thanks.
